---
- name: Enable Files Manager
  uri:
    url: "https://{{ nutanix_host }}:{{ nutanix_port }}/api/nutanix/v3/services/files_manager"
    method: POST
    body:
      state: ENABLE
    validate_certs: "{{ validate_certs }}"
    body_format: json
    status_code: 202
    headers:
      Authorization: "{{ nutanix_api_auth }}"
  register: nutanix_files_mgr_enable

- name: Debug nutanix_files_mgr_enable
  debug:
    var: nutanix_files_mgr_enable
  when:
    - nutanix_debug

- name: Wait for Files Manager enable task to complete
  ansible.builtin.import_role:
    name: grdavies.nutanix_role_prism_monitor_task
  vars:
    nutanix_task_uuid: "{{ nutanix_files_mgr_enable.json.task_uuid }}"
    nutanix_task_retries: 60
    nutanix_task_retry_delay: 15
